version: "3"
services:
  db:
    image: mysql
    container_name: db_margketing
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketing
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
